name: "Mapping logic test"

on:
  workflow_dispatch:
    inputs:
      inventory_file:
        description: inventory_name
        type: choice
        options:
          - windows
          - linux
      windows_template:
        description: template_name
        type: choice
        options:
          - template_windows
          - template_windows1

jobs:
  mapping_logic:
    runs-on: ubuntu-latest
    steps:
      - name: Display selected inventory and template
        run: |
          echo "Selected Inventory: ${{ github.event.inputs.inventory_file }}"
          echo "Selected Template: ${{ github.event.inputs.windows_template }}"
