jobs:
  step1:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Inventory File
        id: collect-inventory-file
        run: |
          echo "::set-output name=inventory_file::${{ github.event.inputs.inventory_file }}"
        shell: bash

  step2:
    needs: step1
    runs-on: ubuntu-latest
    steps:
      - name: Determine Available Templates
        id: determine-templates
        run: |
          inventory_file="${{ needs.step1.outputs.inventory_file }}"
          if [ "$inventory_file" == "windows" ]; then
            templates="template_windows template_windows1"
          elif [ "$inventory_file" == "linux" ]; then
            templates="template_linux template_linux1"
          else
            templates="" # Handle other cases or show an error message
          fi
          echo "::set-output name=available_templates::${templates}"
        shell: bash
