name: "Mapping logic test"

on:
  workflow_dispatch:
    inputs:
      inventory_file:
        description: inventory_name
        type: choice
        options:
          - windows
          - linux

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check inventory file selection
        run: |
          if [[ ${{ github.event.inputs.inventory_file }} == "windows" ]]; then
            echo "Selected inventory file: windows"
            echo "Available templates for windows:"
            echo "template_windows"
          elif [[ ${{ github.event.inputs.inventory_file }} == "linux" ]]; then
            echo "Selected inventory file: linux"
            echo "Available templates for linux:"
            echo "template_linux"
            echo "template_linux1"
          else
            echo "Invalid inventory file selected."
            exit 1
          fi
