on:
  workflow_dispatch:
    inputs:
      inventory_file:
         description: inventory_name
         type: choice
         options:
          - windows
          - linux

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        inventory_file: [windows, linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set template based on inventory file
        id: set-template
        run: |
          if [[ "${{ matrix.inventory_file }}" == "windows" ]]; then
            echo "Selected Template: template_windows,template_windows1"
            echo "::set-output name=template::template_windows,template_windows1"
          else
            echo "Selected Template: template_linux,template_linux1"
            echo "::set-output name=template::template_linux,template_linux1"
          fi

      - name: Use selected template
        run: |
          selected_template="${{ steps.set-template.outputs.template }}"
          # Use the selected template in your workflow
          echo "Selected template: $selected_template"
