name: "Mapping logic test"

on:
  workflow_dispatch:
    inputs:
      zabbix_serverr:
      template_id:
         description: "Enter the template ID Ex:10325"
         type: string
      inventory_file:
         description: inventory_name
         type: choice
         options:
          - windows
          - linux
      Templates:
        description: template_name
        type: choice
           - template_linux
           - template_linux1
