name: "Collect Template and TemplateID"

on:
  workflow_dispatch:
    inputs:
      zabbix_serverr:
      template_id:
         description: "Enter the template ID Ex:10325"
         type: string
      inventory_file:
         description:
         type: choice
         options:
          - windows
          - linux
      Templates:
        - template_linux
        - template_linux1
