name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        options:
          - production
          - staging
          - development
      boolean:
        type: boolean
        description: True or False
      choice:
        type: choice
        description: Make a choice
        options:
          - bar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Conditional Step
        run: |
          # Use a conditional statement to set the options for the 'choice' input
          if [[ "${{ github.event.inputs.environment }}" == "production" ]]; then
            echo "Selected environment is production, so options for 'choice' are 'bar'"
          else
            echo "Selected environment is not production, so options for 'choice' are 'bar', 'foo', 'baz'"
          fi
