name: "Mapping logic test"

on:
  workflow_dispatch:
    inputs:
      inventory_file:
         description: inventory_name
         type: choice
         options:
          - windows
          - linux
      Templates:
        description: template_name
        type: choice
        options:
           - template_linux
           - template_linux1
           - template_windows
           - template_windows1
